Source/QuadBike.Website/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QuadBike.Common.Filters.TripFilter;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Context.CommitProvider;
using QuadBike.Model.ViewModel.Pagination;
using QuadBike.Model.ViewModel.TripViewModels;

namespace QuadBike.Website.Controllers
{
    public class TripController : Controller
    {
        private readonly ITripService _tripService;
        private readonly IUserManagerService _userManagerService;
        private readonly ICommitProvider _commitProvider;

        public TripController(ITripService tripService, IUserManagerService userManagerService, ICommitProvider commitProvider)
        {
            _tripService = tripService;
            _userManagerService = userManagerService;
            _commitProvider = commitProvider;
        }

        public IActionResult Index(string name, int page = 1, SortState sortOrder = SortState.TripNameAsc)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);

            int pageSize = 10;   // количество элементов на странице

            var source = _tripService.GetTripsOfCurrentProvider(userId.Result.Id);

            if (!String.IsNullOrEmpty(name))
            {
                source = source.Where(p => p.TripName.Contains(name));
            }

            switch (sortOrder)
            {
                case SortState.TripNameDesc:
                    source = source.OrderByDescending(s => s.TripName);
                    break;
                case SortState.TypeAsc:
                    source = source.OrderBy(s => s.Type);
                    break;
                case SortState.TypeDesc:
                    source = source.OrderByDescending(s => s.Type);
                    break;
                case SortState.DistanceAsc:
                    source = source.OrderBy(s => s.Distance);
                    break;
                case SortState.DistanceDesc:
                    source = source.OrderByDescending(s => s.Distance);
                    break;
                case SortState.AmountOfPeopleAsc:
                    source = source.OrderBy(s => s.AmountOfPeople);
                    break;
                case SortState.AmountOfPeopleDesc:
                    source = source.OrderByDescending(s => s.AmountOfPeople);
                    break;
                case SortState.StartDateAsc:
                    source = source.OrderBy(s => s.StartDate);
                    break;
                case SortState.StartDateDesc:
                    source = source.OrderByDescending(s => s.StartDate);
                    break;
                case SortState.PriceAsc:
                    source = source.OrderBy(s => s.Price);
                    break;
                case SortState.PriceDesc:
                    source = source.OrderByDescending(s => s.Price);
                    break;

                default:
                    source = source.OrderBy(s => s.TripName);
                    break;
            }

            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            TripViewModel viewModel = new TripViewModel
            {
                PageViewModel = pageViewModel,
                TripFilterViewModel = new TripFilterViewModel(name),
                TripSortViewModel = new TripSortViewModel(sortOrder),
                Trips = items
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TripViewModel trip)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);

            if (ModelState.IsValid)
            {
                if (trip.TripImg != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(trip.TripImg.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)trip.TripImg.Length);
                    }
                    _tripService.CreateTrip(trip, userId.Result.Id, imageData);
                    return RedirectToAction("Index");
                }
            }
            return View(trip);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _tripService.DeleteById(id);
                _commitProvider.Save();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        public IActionResult Edit(int id)
        {
            var res = _tripService.GetTripById(id);

            if (res == null)
            {
                return NotFound();
            }

            ChangeTripViewModel model = new ChangeTripViewModel
            {
                Id = res.Id,
                TripName = res.TripName,
                Type = res.Type,
                Distance = res.Distance,
                AmountOfPeople = res.AmountOfPeople,
                StartDate = res.StartDate,
                EndTrip = res.EndTrip,
                Description = res.Description,
                Price = res.Price
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ChangeTripViewModel model)
        {
            if (ModelState.IsValid)
            {
                var trip = _tripService.GetTripById(model.Id);

                if (trip != null)
                {
                    if (model.TripImg != null)
                    {
                        byte[] imageData = null;
                        using (var binaryReader = new BinaryReader(model.TripImg.OpenReadStream()))
                        {
                            imageData = binaryReader.ReadBytes((int)model.TripImg.Length);
                        }

                        trip.TripName = model.TripName;
                        trip.Type = model.Type;
                        trip.Distance = model.Distance;
                        trip.AmountOfPeople = model.AmountOfPeople;
                        trip.StartDate = model.StartDate;
                        trip.EndTrip = model.EndTrip;
                        trip.Description = model.Description;
                        trip.TripImg = imageData;

                        var result = _tripService.Update(trip);
                        if (result == true)
                        {
                            _commitProvider.Save();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            return View(model);
        }
    }
}

Source/QuadBike.Website/Views/Trip/Create.cshtml
@model QuadBike.Model.ViewModel.TripViewModels.TripViewModel

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-controller="Trip" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="col-7">
        <div class="form-group">
            <label asp-for="TripName"></label><br />
            <input class="form-control" asp-for="TripName" />
            <span asp-validation-for="TripName"></span>
        </div>
        <div class="form-group">
            <label asp-for="Type"></label><br />
            <input class="form-control" asp-for="Type" />
            <span asp-validation-for="Type"></span>
        </div>
        <div class="form-group">
            <label asp-for="Distance"></label><br />
            <input class="form-control" asp-for="Distance" />
            <span asp-validation-for="Distance"></span>
        </div>
        <div class="form-group">
            <label asp-for="AmountOfPeople"></label><br />
            <input class="form-control" asp-for="AmountOfPeople" />
            <span asp-validation-for="AmountOfPeople"></span>
        </div>
        <div class="form-group">
            <label asp-for="StartDate"></label><br />
            <input class="form-control" asp-for="StartDate" />
            <span asp-validation-for="StartDate"></span>
        </div>
        <div class="form-group">
            <label asp-for="EndTrip"></label><br />
            <input class="form-control" asp-for="EndTrip" />
            <span asp-validation-for="EndTrip"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label><br />
            <input class="form-control" asp-for="Description" />
            <span asp-validation-for="Description"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price"></label><br />
            <input class="form-control" asp-for="Price" />
            <span asp-validation-for="Price"></span>
        </div>
        <div class="form-group">
            <label asp-for="TripImg"></label><br />
            <div class="custom-file">
                <input asp-for="TripImg" type="file" name="TripImg" class="custom-file-input" id="inputGroupFile02" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile02">Choose file</label>
            </div>
            <span asp-validation-for="TripImg"></span>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
    </div>
</form>

Source/QuadBike.Website/Views/Trip/Edit.cshtml
@model QuadBike.Model.ViewModel.TripViewModels.ChangeTripViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-controller="Trip" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="TripName" class="control-label">Trip Name</label>
        <input type="text" asp-for="TripName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label">Type</label>
        <input type="text" asp-for="Type" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Distance" class="control-label">Distance</label>
        <input type="number" asp-for="Distance" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AmountOfPeople" class="control-label">Amount of People</label>
        <input type="number" asp-for="AmountOfPeople" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="StartDate" class="control-label">Start Date</label>
        <input type="datetime" asp-for="StartDate" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="EndTrip" class="control-label">EndTrip</label>
        <input type="datetime" asp-for="EndTrip" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Description</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label">Price</label>
        <input type="number" asp-for="Price" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="TripImg"></label><br />
        <input class="form-control" asp-for="TripImg" type="file" name="TripImg" />
        <span asp-validation-for="TripImg"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

Source/QuadBike.Website/Views/Trip/Index.cshtml
@model QuadBike.Model.ViewModel.TripViewModels.TripViewModel
@{
    ViewData["Title"] = "Trips";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="table-responsive">
    <h2>Trips:</h2>
    <form asp-controller="Trip" asp-action="Index" class="form-inline" method="get">
        @Html.TextBox("name", Model.TripFilterViewModel.SelectedName, htmlAttributes: new { @class = "form-control mr-sm-2" })
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Find</button>
    </form>
    <br />

    <table class="table table-hover col-lg-12">
        <thead>
            <tr>
                <th><a asp-action="Index">Img</a></th>
                <th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.TripNameSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Name</a></th>
                @*<th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.TypeSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Type</a></th>*@
                <th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.DistanceSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Distance</a></th>
                <th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.AmountOfPeopleSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Count</a></th>
                <th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.StartDateSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Start</a></th>
                <th><a asp-action="Index">End</a></th>
                <th><a asp-action="Index">Description</a></th>
                <th><a asp-action="Index" asp-route-sortOrder="@(Model.TripSortViewModel.PriceSort)" asp-route-name="@(Model.TripFilterViewModel.SelectedName)">Price</a></th>
                <th></th>
            </tr>
        </thead>
        @foreach (var trip in Model.Trips)
        {
            <tr>
                <td><img class="bd-placeholder-img card-img-top" style="width:50px; height:50px" src="data:image/jpg;base64,@(Convert.ToBase64String(trip.TripImg))" /></td>
                <td style="max-width: 110px">@trip.TripName</td>
                @*<td style="max-width: 100px">@trip.Type</td>*@
                <td>@trip.Distance km</td>
                <td style="max-width: 50px">@trip.AmountOfPeople</td>
                <td>@String.Format("{0:g}", trip.StartDate)</td>
                <td>@String.Format("{0:g}", trip.EndTrip)</td>
                <td style="max-width: 200px">@trip.Description</td>
                <td>@trip.Price $</td>
                <td>
                    <form asp-controller="Trip" asp-action="Delete" asp-route-id="@trip.Id" method="post">
                        <a asp-controller="Trip" asp-action="Edit" asp-route-id="@trip.Id" class="btn btn-sm btn-primary">Update</a>
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
    <page-link page-model="Model.PageViewModel" page-action="Index"></page-link>
    <div>
        <a class="btn btn-primary" asp-controller="Trip" asp-action="Create">Add Trip</a>
    </div>
    <br/><br/>
</div>