Source/QuadBike.Website/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuadBike.DataProvider.Interfaces;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Entities;
using QuadBike.Model.ViewModel.ShoppingViewModel;

namespace QuadBike.Website.Controllers
{
    [Authorize(Roles = "user")]
    public class CartController : Controller
    {

        private readonly IBikeRepository _bikeRepository;
        private readonly ShoppingCart _shoppingCart;

        public CartController(IBikeRepository bikeRepository, ShoppingCart shoppingCart)
        {
            _bikeRepository = bikeRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        //[Route("Cart/AddToShoppingCart/{bikeId:int}")]
        public RedirectToActionResult AddToShoppingCart(int bikeId)
        {
            var selectedBike = _bikeRepository.Get(bikeId);
            if (selectedBike != null)
            {
                _shoppingCart.AddToCart(selectedBike, 1);
            }
            return RedirectToAction("Index");
        }

        [Route("Cart/RemoveFromShoppingCart/{bikeId:int}")]
        public RedirectToActionResult RemoveFromShoppingCart(int bikeId)
        {
            var selectedBike = _bikeRepository.Get(bikeId);
            if (selectedBike != null)
            {
                _shoppingCart.RemoveFromCart(selectedBike);
            }
            return RedirectToAction("Index");
        }
    }
}

Source/QuadBike.Website/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Context.CommitProvider;
using QuadBike.Model.ViewModel.CommentViewModels;

namespace QuadBike.Website.Controllers
{
    public class CommentController : Controller
    {
        public readonly IUserManagerService _userManagerService;
        public readonly ICommentService _commentService;
        private readonly ICommitProvider _commitProvider;

        public CommentController(IUserManagerService userManagerService, ICommentService commentService, ICommitProvider commitProvider)
        {
            _commitProvider = commitProvider;
            _userManagerService = userManagerService;
            _commentService = commentService;
        }

        #region TEST
        [HttpGet]
        public IActionResult Test(string providerId)
        {
            var res = _commentService.GetAllCommentsOfProvider(providerId);
            ViewBag.ProviderId = providerId;
            return View(res);
        }

        [HttpPost]
        public IActionResult Create(CommentViewModel commnent)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);

            if (!ModelState.IsValid)
            {
                var message = ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage);

                return BadRequest(message);
            }
            else
            {
                _commentService.Create(commnent.Content, userId.Result.Id, commnent.AccountId, userId.Result.Email);
                var res = new List<CommentViewModel>();
                res.Add(new CommentViewModel { Content = commnent.Content, AccountId = commnent.AccountId, UserId = userId.Result.Id, UserName = userId.Result.Email, Time = DateTime.Now });
                return PartialView("TestComments", res);
            }
        }

        [HttpDelete]
        public IActionResult Delete(int? CommentId, string AccountId)
        {
            if (CommentId != null)
            {
                _commentService.DeleteById(CommentId);
                _commitProvider.Save();
                var res = _commentService.GetAllCommentsOfProvider(AccountId);
                return PartialView("TestComments", res);
                //return RedirectToAction("Test");
            }
            else
            {
                return BadRequest();
            }
        }
        #endregion
    }
}

Source/QuadBike.Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.ViewModel.Pagination;
using QuadBike.Website.Models;

namespace QuadBike.Website.Controllers
{
    public class HomeController : Controller
    {
        private IBikeService _bikeService;
        private ITripService _tripService;
        private IUserManagerService _userManagerService;

        public HomeController(IBikeService bikeService, ITripService tripService, IUserManagerService userManagerService)
        {
            _bikeService = bikeService;
            _tripService = tripService;
            _userManagerService = userManagerService;
        }

        public IActionResult Index(int page = 1)
        {
            int pageSize = 9;   // количество элементов на странице

            // var source = _bikeService.GetAllBikes();
            var source = _bikeService.GetBikesWithProviderInfo();
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Bikes = items
            };
            return View(viewModel);
        }

        public IActionResult IndexPartial(int page = 1)
        {
            int pageSize = 9;   // количество элементов на странице

            // var source = _bikeService.GetAllBikes();
            var source = _bikeService.GetBikesWithProviderInfo();
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Bikes = items
            };
            return PartialView(viewModel);
        }

        public IActionResult IndexData(int page = 1)
        {
            int pageSize = 9;   // количество элементов на странице

            // var source = _bikeService.GetAllBikes();
            var source = _bikeService.GetBikesWithProviderInfo();
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Bikes = items
            };
            return View(viewModel);
        }

        public IActionResult ListTrips(int page = 1)
        {
            int pageSize = 6;   // количество элементов на странице

            var source = _tripService.GetAllTrips();
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexTripViewModel viewModel = new IndexTripViewModel
            {
                PageViewModel = pageViewModel,
                Trips = items
            };
            return View(viewModel);
        }

        public IActionResult ProviderList(int page = 1)
        {
            int pageSize = 8;

            var source = _userManagerService.AllProviderByRoleName("provider");
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            ProviderListViewModel viewModel = new ProviderListViewModel()
            {
                PageViewModel = pageViewModel,
                Accounts = items
            };
            return View(viewModel);
        }

        public IActionResult ProviderBike(string accId)
        {
            var res = _userManagerService.GetProviderOfBike(accId);
            return View(res);
        }

        public IActionResult ProviderTrip(string tripId)
        {
            var res = _userManagerService.GetProviderOfTrip(tripId);
            return View(res);
        }

        [HttpGet]
        public IActionResult CheckEmailIndex()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BikesOfCurrentProvider(string providerId)
        {
            var res = _bikeService.GetBikesOfCurrentProvider(providerId);
            return View(res);
        }

        [HttpGet]
        public IActionResult TripsOfCurrentProvider(string providerId)
        {
            var res = _tripService.GetTripsOfCurrentProvider(providerId);
            return View(res);
        }
    }
}

Source/QuadBike.Website/Views/Home/BikesOfCurrentProvider.cshtml
@model IEnumerable<QuadBike.Model.Entities.Bike>

@{
    ViewData["Title"] = "BikesOfCurrentProvider";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="album bg-light">
    <div class="container">
        <div class="row">
            @foreach (var u in Model)
            {
            <div class="col-md-4 align-self-between">
                <div class="card mb-4 shadow-sm">
                    @if (u.BikeImg != null)
                    {
                        <div class="view view-cascade overlay">
                            <img class="bd-placeholder-img card-img-top" style="width:100%; height:225px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.BikeImg))" alt="Card image cap" />
                            <a>
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                    }
                    <div class="card-body card-body-cascade">
                        <p class="card-text">
                            <div>
                                <b>Name:</b> @u.Name
                            </div>
                            <div>
                                <b>Type Engine:</b> @u.TypeEngine
                            </div>
                            <div>
                                <b>Max Speed:</b> @u.MaxSpeed km / hour
                            </div>
                            <div>
                                <b>Power:</b> @u.Power
                            </div>
                            <div>
                                <b>Fuel:</b> @u.Fuel
                            </div>
                            <div>
                                <b>Description:</b> @u.Description
                            </div>
                            <div>
                                <b>Price:</b> @u.Price $ per one day
                            </div>
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="ProviderBike" asp-route-accId="@u.AccountId">Contact us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

Source/QuadBike.Website/Views/Home/CheckEmailIndex.cshtml
@{
    ViewData["Title"] = "CheckEmailIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1 class="display-4">Hi, new user!</h1>
    <p class="lead">To complete the registration, check the email and click on the link indicated in the letter.</p>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" asp-controller='Home' asp-action='Index'>Return to Home</a>
</div>

Source/QuadBike.Website/Views/Home/Index.cshtml
@using QuadBike.Model.Entities
@model QuadBike.Model.ViewModel.Pagination.IndexViewModel

@addTagHelper "*, QuadBike.Website"

@{
    ViewData["Title"] = "Home Page";
}
@*<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/jquery-ui.min.js"></script>*@
@*<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/sunny/jquery-ui.css">*@
@*<script type="text/javascript" src="~/vendor/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js"></script>
    <link rel="stylesheet" href="css/bootstrap-datetimepicker.min.css" />*@
@*https://trentrichardson.com/examples/timepicker/*@

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css" />
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>

<div class="album bg-light">
    <div class="container">
        <div class="jumbotron mt-4">
            <h4>ATV marketplace</h4>
            <p class="lead">
                Quad bikes are vehicles designed for off-road use.
                They are not suited for travelling on public roads, mostly because they are light and offer little protection from other vehicles.
                But we want to solve this situation giving you a chance to enjoy this type of transport.
            </p>
            <a class="btn btn-primary" asp-controller="Home" asp-action="ListTrips" role="button">See trips »</a>
        </div>
        <br />

        <div id="bikeTemp">
            @{Html.RenderPartial("PartialBikeIndex", Model);}
        </div>

    </div>
</div>

<script type="text/javascript">
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
<script type="text/javascript">
    $(document).ready(function () {
        if ($('#popupdiv').html() != '') {
            $("#popupdiv").show();
        }
    });

    $(function () {

        $.datepicker.setDefaults($.datepicker.regional['en']);
        $('#startTime').datetimepicker(
            {
                onSelect: function (date) {
                    var dt1 = $('#startTime').datepicker('getDate');
                    var dt2 = $('#endTime').datepicker('getDate');
                    if (dt1 > dt2) {
                        $('#endTime').datepicker('setDate', dt1);
                    }
                    $('#endTime').datepicker('option', 'minDate', dt1);
                },
                controlType: 'select',
                oneLine: true,
                timeFormat: 'hh:mm tt',
                showTime: true,
                format: 'dd/MM/yyyy hh:mm:ss',
                numberOfMonths: [1, 2],
                constrainInput: true,
                changeMonth: true,
                changeYear: true,
                yearRange: '2019:2100',
                pickTime: true,
                minDate: "+0",
                maxDate: "+31",
                showTime: true
            });
        $('#endTime').datetimepicker(
            {
                onSelect: function (date) {
                    var dt1 = $('#startTime').datepicker('getDate');
                    var dt2 = $('#endTime').datepicker('getDate');
                    if (dt1 < dt2) {
                        $('#endTime').datepicker('setDate', dt2);
                    }
                    $('#endTime').datepicker('option', 'minDate', dt2);
                },
                showTime: true,
                format: 'dd/MM/yyyy hh:mm:ss',
                numberOfMonths: [1, 2],
                constrainInput: true,
                changeMonth: true,
                changeYear: true,
                yearRange: '2019:2100',
                pickTime: true,
                minDate: "+0",
                maxDate: "+31",
                showTime: true,
                addSliderAccess: true,
                sliderAccessArgs: { touchonly: false }
            });
    });
</script>

Source/QuadBike.Website/Views/Home/Index2.cshtml
@using QuadBike.Model.Entities
@model QuadBike.Model.ViewModel.Pagination.IndexTripViewModel

@addTagHelper "*, QuadBike.Website"

@{
    ViewData["Title"] = "Trips Page";
}

<div class="album bg-light">
    <div class="container">
        <div class="row">
            @foreach (Trip u in Model.Trips)
            {
                <div class="col-md-6">
                    <div class="card mb-4 shadow-sm">
                        @if (u.TripImg != null)
                        {
                            <img class="bd-placeholder-img card-img-top" style="width:100%; height:325px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.TripImg))" />
                        }
                        <div class="card-body">
                            <p class="card-text">
                                <div>
                                    <b>Name:</b> @u.TripName
                                </div>
                                <div>
                                    <b>Type:</b> @u.Type
                                </div>
                                <div>
                                    <b>Distance:</b> @u.Distance km
                                </div>
                                <div>
                                    <b>Amount of people:</b> @u.AmountOfPeople
                                </div>
                                <div>
                                    <b>Start:</b> @u.StartDate
                                </div>
                                <div>
                                    <b>End:</b> @u.EndTrip
                                </div>
                                <div>
                                    <b>Description:</b> @u.Description
                                </div>
                                <div>
                                    <b>Price:</b> @u.Price $
                                </div>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Contact us</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <page-link page-model="Model.PageViewModel" page-action="View"></page-link>
    </div>
</div>

Source/QuadBike.Website/Views/Home/PartialBikeIndex.cshtml
@model QuadBike.Model.ViewModel.Pagination.IndexViewModel
@addTagHelper "*, QuadBike.Website"

<div class="row">
    @foreach (var u in Model.Bikes)
    {
        <div class="col-md-4 align-self-between">
            <div class="card mb-4 shadow-sm">
                @if (u.BikeImg != null)
                {
                    <div class="view view-cascade overlay">
                        <img class="bd-placeholder-img card-img-top" style="width:100%; height:225px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.BikeImg))" alt="Card image cap" />
                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                }
                <div class="card-body card-body-cascade">
                    <p class="card-text">
                        <div>
                            <b>Name:</b> @u.Name
                        </div>
                        <div>
                            <b>Type Engine:</b> @u.TypeEngine
                        </div>
                        <div>
                            <b>Max Speed:</b> @u.MaxSpeed km / hour
                        </div>
                        <div>
                            <b>Power:</b> @u.Power
                        </div>
                        <div>
                            <b>Fuel:</b> @u.Fuel
                        </div>
                        <div>
                            <b>Description:</b> @u.Description
                        </div>
                        <div>
                            <b>Price:</b> @u.Price $ per one day
                        </div>
                        <div class="btn-group">
                            <b>Provider:&nbsp</b> <a asp-controller="Home" asp-action="ProviderBike" asp-route-accId="@u.AccountId"> @u.Email</a>
                        </div>
                    </p>
                    <hr />
                    <div class="d-flex justify-content-between align-items-center">
                        <form class="needs-validation" asp-controller="Cart" asp-action="AddToShoppingCart" asp-route-bikeId="@u.Id" novalidate>
                            <div class="form-groupe">
                                <label><b>Date Start</b></label>
                                <input class="form-control mb-2" id="startTime" placeholder="Date start" required>
                                <span class="invalid-feedback">
                                    Cannot be empty!
                                </span>
                            </div>

                            <div class="form-groupe">
                                <label><b>Date End</b></label>
                                <input class="form-control mb-2" id="endTime" placeholder="Date end" required>
                                <span class="invalid-feedback">
                                    Cannot be empty!
                                </span>
                            </div>
                            <button class="btn btn-sm btn-outline-success" type="submit">Rent</button>
                            @*<a class="btn btn-sm btn-outline-success" asp-controller="Cart" asp-action="AddToShoppingCart" asp-route-bikeId="@u.Id">Rent</a>*@
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<page-link page-model="Model.PageViewModel"></page-link>

<script type="text/javascript">  
    $('.page-link').click(function () {
        debugger;
        var currentPage = $(this).val();
        $.ajax({
            type: 'POST',
            url: '/Home/IndexPartial',
            data: {
                pageNumber: currentPage
            },
            success: function (data) {
                alert("Succeess!");
                $('#bikeTemp').append(data);
            },
        });
    });
</script>

Source/QuadBike.Website/Views/Home/ProviderBike.cshtml
@model List<QuadBike.Model.Entities.Account>

@{
    ViewData["Title"] = "ProviderBike";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="album bg-light">
    <div class="container">
        <div class="row">
            @foreach (var u in Model)
            {
                <div class="card flex-row flex-wrap col-md-6">
                    <div class="card-header border-0">
                        @if (u.AccountImg != null)
                        {
                            <div class="card-img">
                                <img class="bd-placeholder-img" style="width:200px; height:180px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.AccountImg))" alt="Card image cap" />
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        }
                    </div>
                    <div class="card-block px-2">
                        <p class="card-text">
                            <div>
                                <b>Name:</b> @u.Name
                            </div>
                            <div>
                                <b>Mobile:</b> @u.PhoneNumber
                            </div>
                            <div>
                                <b>Description:</b> @u.Description
                            </div>
                            <div>
                                <b>Email:</b> @u.Email
                            </div>
                        </p>
                        <div>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="BikesOfCurrentProvider" asp-route-providerId="@u.Id">View Bikes</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="TripsOfCurrentProvider" asp-route-providerId="@u.Id">View Trips</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Comment" asp-action="Index" asp-route-providerId="@u.Id">Comments</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Source/QuadBike.Website/Views/Home/ProviderList.cshtml
@model QuadBike.Model.ViewModel.Pagination.ProviderListViewModel

@{
    ViewData["Title"] = "ProviderList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="album bg-light">
    <div class="container">
        <div class="row">
            @foreach (var u in Model.Accounts)
            {
                <div class="card flex-row flex-wrap col-md-6">
                    <div class="card-header border-0">
                        @if (u.AccountImg != null)
                        {
                            <div class="card-img">
                                <img class="bd-placeholder-img" style="width:200px; height:180px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.AccountImg))" alt="Card image cap" />
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        }
                    </div>
                    <div class="card-block px-2">
                        <p class="card-text">
                            <div>
                                <b>Name:</b> @u.Name
                            </div>
                            <div>
                                <b>Mobile:</b> @u.PhoneNumber
                            </div>
                            <div>
                                <b>Description:</b> @u.Description
                            </div>
                            <div>
                                <b>Email:</b> @u.Email
                            </div>
                        </p>
                        <div>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="BikesOfCurrentProvider" asp-route-providerId="@u.Id">View Bikes</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="TripsOfCurrentProvider" asp-route-providerId="@u.Id">View Trips</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Comment" asp-action="Index" asp-route-providerId="@u.Id">Comments</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Comment" asp-action="Test" asp-route-providerId="@u.Id">Test</a>
                        </div>
                    </div>
                </div>
            }
        </div>
        <page-link page-model="Model.PageViewModel" page-action="ProviderList"></page-link>
    </div>
</div>
<br />

Source/QuadBike.Website/Views/Home/ProviderTrip.cshtml
@model List<QuadBike.Model.Entities.Account>

@{
    ViewData["Title"] = "ProviderTrip";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="album bg-light">
    <div class="container">
        <div class="row">
            @foreach (var u in Model)
            {
                <div class="card flex-row flex-wrap col-md-6">
                    <div class="card-header border-0">
                        @if (u.AccountImg != null)
                        {
                            <div class="card-img">
                                <img class="bd-placeholder-img" style="width:200px; height:180px" src="data:image/jpg;base64,@(Convert.ToBase64String(u.AccountImg))" alt="Card image cap" />
                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                        }
                    </div>
                    <div class="card-block px-2">
                        <p class="card-text">
                            <div>
                                <b>Name:</b> @u.Name
                            </div>
                            <div>
                                <b>Mobile:</b> @u.PhoneNumber
                            </div>
                            <div>
                                <b>Description:</b> @u.Description
                            </div>
                            <div>
                                <b>Email:</b> @u.Email
                            </div>
                        </p>
                        <div>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="BikesOfCurrentProvider" asp-route-providerId="@u.Id">View Bikes</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Home" asp-action="TripsOfCurrentProvider" asp-route-providerId="@u.Id">View Trips</a>
                            <a class="btn btn-sm btn-outline-secondary" asp-controller="Comment" asp-action="Index" asp-route-providerId="@u.Id">Comments</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>