Source/QuadBike.Website/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuadBike.Common.Filters.BikeFilter;
using QuadBike.Common.Filters.OrderFilter;
using QuadBike.DataProvider.Interfaces;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Context.CommitProvider;
using QuadBike.Model.ViewModel.BikeViewModels;
using QuadBike.Model.ViewModel.OrderViewModels;
using QuadBike.Model.ViewModel.Pagination;

namespace QuadBike.Website.Controllers
{
    [Authorize(Roles = "provider")]
    public class BikeController : Controller
    {
        private readonly IBikeService _bikeService;
        private readonly IOrderRepository _orderRepository;
        private readonly IOrderService _orderService;
        private readonly IUserManagerService _userManagerService;
        private readonly ICommitProvider _commitProvider;

        public BikeController(IBikeService bikeService, IUserManagerService userManagerService, ICommitProvider commitProvider, IOrderRepository orderRepository, IOrderService orderService)
        {
            _bikeService = bikeService;
            _userManagerService = userManagerService;
            _commitProvider = commitProvider;
            _orderRepository = orderRepository;
            _orderService = orderService;
        }

        public IActionResult Index(string name, int page = 1, SortState sortOrder = SortState.NameAsc)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);

            int pageSize = 10;

            var source = _bikeService.GetBikesOfCurrentProvider(userId.Result.Id);

            if (!String.IsNullOrEmpty(name))
            {
                source = source.Where(p => p.Name.Contains(name));
            }

            switch (sortOrder)
            {
                case SortState.NameDesc:
                    source = source.OrderByDescending(s => s.Name);
                    break;
                case SortState.MaxSpeedAsc:
                    source = source.OrderBy(s => s.MaxSpeed);
                    break;
                case SortState.MaxSpeedDesc:
                    source = source.OrderByDescending(s => s.MaxSpeed);
                    break;
                case SortState.TypeEngineAsc:
                    source = source.OrderBy(s => s.TypeEngine);
                    break;
                case SortState.TypeEngineDesc:
                    source = source.OrderByDescending(s => s.TypeEngine);
                    break;
                case SortState.PowerAsc:
                    source = source.OrderBy(s => s.Power);
                    break;
                case SortState.PowerDesc:
                    source = source.OrderByDescending(s => s.Power);
                    break;
                case SortState.FuelAsc:
                    source = source.OrderBy(s => s.Fuel);
                    break;
                case SortState.FuelDesc:
                    source = source.OrderByDescending(s => s.Fuel);
                    break;
                case SortState.PriceAsc:
                    source = source.OrderBy(s => s.Price);
                    break;
                case SortState.PriceDesc:
                    source = source.OrderByDescending(s => s.Price);
                    break;

                default:
                    source = source.OrderBy(s => s.Name);
                    break;
            }

            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            BikeViewModel viewModel = new BikeViewModel
            {
                PageViewModel = pageViewModel,
                BikeFilterViewModel = new BikeFilterViewModel(name),
                BikeSortViewModel = new BikeSortViewModel(sortOrder),
                Bikes = items
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _bikeService.DeleteById(id);
                _commitProvider.Save();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Create(BikeViewModel bike)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);

            if (ModelState.IsValid)
            {
                if (bike.BikeImg != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(bike.BikeImg.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)bike.BikeImg.Length);
                    }
                    _bikeService.CreateBike(bike, userId.Result.Id, imageData);
                    return RedirectToAction("Index");
                }
            }
            return View(bike);
        }

        public IActionResult Edit(int id)
        {
            var res = _bikeService.GetBikeById(id);

            if (res == null)
            {
                return NotFound();
            }

            ChangeBikeViewModel model = new ChangeBikeViewModel
            {
                Id = res.Id,
                Name = res.Name,
                MaxSpeed = res.MaxSpeed,
                TypeEngine = res.TypeEngine,
                Power = res.Power,
                Fuel = res.Fuel,
                Description = res.Description,
                Price = res.Price
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ChangeBikeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var bike = _bikeService.GetBikeById(model.Id);

                if (bike != null)
                {
                    if (model.BikeImg != null)
                    {
                        byte[] imageData = null;
                        using (var binaryReader = new BinaryReader(model.BikeImg.OpenReadStream()))
                        {
                            imageData = binaryReader.ReadBytes((int)model.BikeImg.Length);
                        }

                        bike.Name = model.Name;
                        bike.MaxSpeed = model.MaxSpeed;
                        bike.TypeEngine = model.TypeEngine;
                        bike.Power = model.Power;
                        bike.Fuel = model.Fuel;
                        bike.Description = model.Description;
                        bike.Price = model.Price;
                        bike.BikeImg = imageData;

                        var result = _bikeService.Update(bike);
                        if (result == true)
                        {
                            _commitProvider.Save();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult OrderList(string name, int page = 1, SortStateTwo sortOrderTwo = SortStateTwo.NameAsc)
        {
            int pageSize = 10;
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);
            var source = _orderService.OrdersForCurrentProvider(userId.Result.Id);

            if (!String.IsNullOrEmpty(name))
            {
                source = source.Where(p => p.Name.Contains(name));
            }

            // сортировка
            switch (sortOrderTwo)
            {
                case SortStateTwo.NameDesc:
                    source = source.OrderByDescending(s => s.Name);
                    break;
                case SortStateTwo.DateAsc:
                    source = source.OrderBy(s => s.OrderPlaced);
                    break;
                case SortStateTwo.DateDesc:
                    source = source.OrderByDescending(s => s.OrderPlaced);
                    break;
                default:
                    source = source.OrderBy(s => s.Name);
                    break;
            }


            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            OrderViewModel viewModel = new OrderViewModel()
            {
                PageViewModel = pageViewModel,
                OrderFilterViewModel = new OrderFilterViewModel(name),
                OrderSortViewModel = new OrderSortViewModel(sortOrderTwo),
                Orders = items
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult InfoOrderList(int id)
        {
            var currentUserName = User.Identity.Name;
            var userId = _userManagerService.GetUserByName(currentUserName);
            var res = _orderService.OrderDetailsOfOrderById(id, userId.Result.Id);
            return View(res);
        }

        [HttpGet]
        public IActionResult ContactProvider(string id)
        {
            var res = _userManagerService.GetUserById(id);
            return View(res);
        }

        [HttpPost]
        public IActionResult DeleteOrder(int? orderId)
        {
            if (orderId != null)
            {
                _orderService.DeleteOrderById(orderId);

Source/QuadBike.Website/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuadBike.DataProvider.Interfaces;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Entities;
using QuadBike.Model.ViewModel.ShoppingViewModel;

namespace QuadBike.Website.Controllers
{
    [Authorize(Roles = "user")]
    public class CartController : Controller
    {

        private readonly IBikeRepository _bikeRepository;
        private readonly ShoppingCart _shoppingCart;

        public CartController(IBikeRepository bikeRepository, ShoppingCart shoppingCart)
        {
            _bikeRepository = bikeRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        //[Route("Cart/AddToShoppingCart/{bikeId:int}")]
        public RedirectToActionResult AddToShoppingCart(int bikeId)
        {
            var selectedBike = _bikeRepository.Get(bikeId);
            if (selectedBike != null)
            {
                _shoppingCart.AddToCart(selectedBike, 1);
            }
            return RedirectToAction("Index");
        }

        [Route("Cart/RemoveFromShoppingCart/{bikeId:int}")]
        public RedirectToActionResult RemoveFromShoppingCart(int bikeId)
        {
            var selectedBike = _bikeRepository.Get(bikeId);
            if (selectedBike != null)
            {
                _shoppingCart.RemoveFromCart(selectedBike);
            }
            return RedirectToAction("Index");
        }
    }
}

Source/QuadBike.Website/Controllers/ModerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuadBike.Logic.Interfaces;
using QuadBike.Model.Context.CommitProvider;
using QuadBike.Model.ViewModel.ModerViewModels;
using QuadBike.Model.ViewModel.Pagination;

namespace QuadBike.Website.Controllers
{
    [Authorize(Roles = "moderator")]
    public class ModerController : Controller
    {
        private readonly IUserManagerService _userManagerService;
        private readonly ICommitProvider _commitProvider;

        public ModerController(IUserManagerService userManagerService, ICommitProvider commitProvider)
        {
            _userManagerService = userManagerService;
            _commitProvider = commitProvider;
        }

        public IActionResult Index()
        {
            return View(_userManagerService.ShowListOfRoles());
        }

        public IActionResult UserList(int page = 1)
        {

            int pageSize = 10;   // количество элементов на странице

            var source = _userManagerService.ShowListUsers();
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            AccountViewModel viewModel = new AccountViewModel
            {
                PageViewModel = pageViewModel,
                Accounts = items
            };
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            var account = _userManagerService.GetUserById(userId);
            if (account != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManagerService.GetRolesByAccount(userId);
                var allRoles = _userManagerService.ShowListOfRoles();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = account.Result.Id,
                    UserEmail = account.Result.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            var account = _userManagerService.FindByIdRole(userId);

            if (account != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManagerService.GetRolesByAccount(userId);
                // получаем все роли
                var allRoles = _userManagerService.ShowListOfRoles();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManagerService.AddToRole(userId, addedRoles);

                await _userManagerService.RemovedFromRoles(userId, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<ActionResult> Delete(string userId)
        {
            var account = await _userManagerService.GetUserById(userId);
            if (account != null)
            {
                IdentityResult result = await _userManagerService.DeleteAccount(account);
                _commitProvider.Save();
            }
            return RedirectToAction("UserList");
        }
    }
}

Source/QuadBike.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css" />
    <script type="text/javascript" src="~/vendor/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/vendor/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/vendor/bootstrap/dist/js/bootstrap.bundle.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img class="navbar-brand" style="height:auto" src="~/logo.png" width="200" />
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverses" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" style="font-size:larger">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="ListTrips" style="font-size:larger">Trips</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="ProviderList" style="font-size:larger">Providers</a>
                        </li>
                        @if (User.IsInRole("user"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index" style="font-size:larger">Cart</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-success" data-toggle="dropdown" href="#" id="dropdownMenuButton" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <p class="dropdown-header">Settings</p>
                                    <div class="dropdown-divider"></div>
                                    @if (User.IsInRole("moderator"))
                                    {
                                        <a asp-controller="Moder" asp-action="Index" class="dropdown-item">Roles list</a>
                                        <a asp-controller="Moder" asp-action="UserList" class="dropdown-item">Users list</a>
                                    }
                                    else if (User.IsInRole("provider"))
                                    {
                                        <a class="dropdown-item" asp-controller="Bike" asp-action="Index">Bikes List</a>
                                        <a class="dropdown-item" asp-controller="Trip" asp-action="Index">Trips List</a>
                                        <a class="dropdown-item" asp-controller="Bike" asp-action="OrderList">Orders List</a>
                                    }
                                    else if (User.IsInRole("user"))
                                    {
                                    }
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Index">Update Account</a>
                                    <div class="dropdown-divider"></div>
                                    <form method="post" asp-controller="Account" asp-action="LogOff">
                                        <input class="dropdown-item text-danger" type="submit" value="Log Off" />
                                    </form>
                                </div>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item">
                                <a class="btn btn-outline-success" asp-controller="Account" asp-action="Login">Sign Up</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <main style="width: 100%" role="main">
        <div style="width: 100%" class="container body-content">
            @RenderBody()
        </div>
    </main>
    <br />
    <footer class="footer mt-auto py-3">
        <div class="container">
            @*<div id="map-container-google-11" class="z-depth-1-half map-container-6" style="height: 800px">
                    <iframe src="https://maps.google.com/maps?q=new%20minsk&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
                <br>*@
            <p>&copy; 2019 - Stay with us</p>
        </div>
    </footer>
</body>
</html>